INSERT INTO banks (name, bank_id, atm_bin, card_length, short_name, bank_code, type, swift_code) VALUES
                                                                                                     ('Visa', '4', '4', 13, 'Visa', '', '', ''),
                                                                                                     ('MasterCard', '5', '5', 16, 'MasterCard', '', '', ''),
                                                                                                     ('Ngân hàng An Bình', '970425', '970425', 16, 'ABBank', '323', 'ACC', 'ABBKVNVX'),
                                                                                                     ('Ngân hàng Á Châu', '970416', '970416', 0, 'ACB', '307', 'ACC', 'ASCBVNVX'),
                                                                                                     ('Ngân hàng NN & PTNT VN', '970405', '970499', 16, 'Agribank, VBARD', '204', 'ACC', 'VBAAVNVX'),
                                                                                                     ('Ngân hàng TMCP Bảo Việt', '970438', '970438', 20, 'Baoviet Bank', '359', 'ACC', 'BVBVVNVX'),
                                                                                                     ('Ngân hàng Đầu tư và Phát triển Việt Nam', '970418', '970418', 16, 'BIDV', '202', 'ACC', 'BIDVVNVX'),
                                                                                                     ('Ngân hàng Đông Á', '970406', '970406', 16, 'Dong A Bank, DAB', '304', 'ACC', 'EACBVNVX'),
                                                                                                     ('Ngân hàng Xuất nhập khẩu Việt Nam', '970431', '970431', 16, 'Eximbank, EIB', '305', 'ACC', 'EBVIVNVX'),
                                                                                                     ('Ngân hàng Dầu khí Toàn cầu', '970408', '970408', 20, 'GP Bank', '320', 'ACC', 'GBNKVNVX'),
                                                                                                     ('Ngân hàng Phát triển TP HCM', '970437', '970437', 20, 'HDBank', '321', 'ACC', 'HDBCVNVX'),
                                                                                                     ('Ngân hàng Hong Leong Viet Nam', '970442', '970442', 20, 'HLO', '603', 'ACC', 'HLBBVNVX'),
                                                                                                     ('Indovina Bank', '970434', '888999', 0, 'IVB', '502', 'ACC', 'IVBKVNVX'),
                                                                                                     ('Ngân hàng Kiên Long', '970452', '970452', 16, 'Kienlongbank', '353', 'ACC', 'KLBKVNVX'),
                                                                                                     ('Ngan hàng TMCP Bưu điện Liên Việt', '970449', '970449', 0, 'Lienvietbank, LPB', '357', 'ACC', 'LVBKVNVX'),
                                                                                                     ('Ngân hàng Hàng Hải Việt Nam', '970426', '970426', 16, 'Maritime Bank, MSB', '302', 'ACC', 'MCOBVNVX'),
                                                                                                     ('Ngân hàng Quân Đội', '970422', '970422', 16, 'MB', '311', 'ACC', 'MSCBVNVX'),
                                                                                                     ('Ngân hàng Nam Á', '970428', '970428', 0, 'Nam A Bank, NAB', '306', 'ACC', 'NABVVNVX'),
                                                                                                     ('Ngân hàng Bắc Á', '970409', '970409', 0, 'NASBank, NASB', '313', 'ACC', 'NASBVNVX'),
                                                                                                     ('Ngân hàng Quoc Dan', '970419', '970419', 16, 'NCB', '352', 'ACC', 'NVBAVNVX'),
                                                                                                     ('Ngân hàng Đại Dương', '970414', '970414', 20, 'Ocean Bank', '319', 'ACC', 'OJBAVNVX'),
                                                                                                     ('Ngân hàng Phương Đông', '970448', '970468', 16, 'Oricombank, OCB, PhuongDong Bank', '333', 'ACC', 'ORCOVNVX'),
                                                                                                     ('Ngân hàng Xăng dầu Petrolimex', '970430', '970430', 16, 'PG Bank', '341', 'ACC', 'PGBNVNVX'),
                                                                                                     ('NH TMCP Đại Chúng Viet Nam', '970412', '970412', 16, 'PVcombank', '360', 'ACC', 'WBVNVNVX'),
                                                                                                     ('Ngân hàng Sài Gòn Thương Tín', '970403', '970403', 16, 'Sacombank', '303', 'ACC', 'SGTTVNVX'),
                                                                                                     ('Ngân hàng Sài Gòn Công Thương', '970400', '161087', 16, 'Saigonbank', '308', 'ACC', 'SBITVNVX'),
                                                                                                     ('Ngân hàng TMCP Sài Gòn', '970429', '970429', 16, 'SCB', '334', 'ACC', 'SACLVNVX'),
                                                                                                     ('Ngân hàng TMCP Đông Nam Á', '970440', '970468', 16, 'SeABank', '317', 'ACC', 'SEAVVNVX'),
                                                                                                     ('Ngân hàng Sài Gòn - Hà Nội', '970443', '970443', 16, 'SHB', '348', 'ACC', 'SHBKVNVX'),
                                                                                                     ('Ngân hàng TNHH MTV Shinhan Việt Nam', '970424', '970424', 0, 'Shinhan Bank', '616', 'ACC', 'SHBKVNVX'),
                                                                                                     ('Ngân hàng Kỹ thương Việt Nam', '970407', '970407', 16, 'Techcombank, TCB', '310', 'ACC', 'VTCBVNVX'),
                                                                                                     ('United Oversea Bank', '970458', '970458', 0, 'UOB', '618', 'ACC', 'UOVBVNVX'),
                                                                                                     ('Ngân hàng Quốc tế', '970441', '970441', 0, 'VIBank, VIB', '314', 'ACC', 'VNIBVNVX'),
                                                                                                     ('Ngân hàng VID Public', '970439', '970439', 16, 'VID public', '501', 'ACC', ''),
                                                                                                     ('Ngân hàng Việt Á', '970427', '970427', 0, 'VietA Bank, VAB', '355', 'ACC', 'VNACVNVX'),
                                                                                                     ('Ngân hàng Việt Nam Thương Tín', '970433', '970433', 16, 'Vietbank', '356', 'ACC', 'VNTTVNVX'),
                                                                                                     ('NHTMCP Bản Việt', '970454', '970454', 16, 'VietCapital Bank', '327', 'ACC', 'VCBCVNVX'),
                                                                                                     ('Ngân hàng TMCP Ngoại Thương', '970436', '970436', 0, 'Vietcombank, VCB', '203', 'ACC', 'BFTVVNVX'),
                                                                                                     ('Ngân hàng công thương Việt Nam', '970415', '970415', 16, 'Vietinbank', '201', 'ACC', 'ICBVVNVX'),
                                                                                                     ('Ngân hàng Thương mại cổ phần Việt Nam Thịnh Vượng', '970432', '970432', 16, 'VPBank', '309', 'ACC', 'VPBKVNVX'),
                                                                                                     ('Ngân hàng Liên doanh Việt Nga', '970421', '970421', 16, 'VRB', '505', 'ACC', 'VJRBVNVX'),
                                                                                                     ('WOORI BANK Hà Nội', '970457', '970457', 0, 'WHHN', '624', 'ACC', 'HVBKVNVX');